sonar.projectKey=urlshortner-microservices
sonar.organization=ziadhosain-oss
sonar.projectName=URL Shortener Microservices
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/k8s/**,**/vendor/**
sonar.python.version=3.11